
services:
  redis:
    container_name: redis
    image: redis:8.2.3-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    env_file: [".env"]
    ports:
      - "6379:6379"
    networks:
      - web-app-automoviles

networks:
  web-app-automoviles:
    external: true